---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHc4b202OHRwCg==
  CLOUDINARY_KEY: NDg0NDIxNDM1NjQ5NDM4Cg==
  CLOUDINARY_SECRET: QzRzNmZ0aW1UblNvS0RQMHN0cEhqb3Yydm5zCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2ljMmhoWm1WNllXNXpZWEpwSWl3aVlTSTZJbU50TjJ0a2RIaGlhVEEyYm5veWEzTmpiV0oyYzNkaE1qa2lmUS5ZYlh2Y2RzTGgyQkt1ZEc3Q0JrZEtRCg==
  DB_URL: bW9uZ29kYitzcnY6Ly9zaGFmZXphbnNhcmk6UGNYb091dWFMd1VhRkp6M0AzLXRpZXItcHJvamVjdC5ycnR0Zi5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9My1UaWVyLVByb2plY3QK
  SECRET: My1UaWVyLVByb2plY3QK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: adijaiswal/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
