---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHc4b202OHRwCg==
  CLOUDINARY_KEY: NDg0NDIxNDM1NjQ5NDM4Cg==
  CLOUDINARY_SECRET: QzRzNmZ0aW1UblNvS0RQMHN0cEhqb3Yydm5zCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2ljMmhoWm1WNllXNXpZWEpwSWl3aVlTSTZJbU50TjJ0a2RIaGlhVEEyYm5veWEzTmpiV0oyYzNkaE1qa2lmUS5ZYlh2Y2RzTGgyQkt1ZEc3Q0JrZEtRCg==
  DB_URL: bW9uZ29kYitzcnY6Ly9zaGFmZXphbnNhcmk6UGNYb091dWFMd1VhRkp6M0AzLXRpZXItcHJvamVjdC5ycnR0Zi5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9My1UaWVyLVByb2plY3QK
  SECRET: My1UaWVyLVByb2plY3QK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: shafaiz/campa:latest  # ✅ Corrected image name
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          resources:  # ✅ Added resource limits
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:  # ✅ Updated liveness probe
            httpGet:
              path: /health  # Agar app me health route hai to use karein
              port: 3000
            initialDelaySeconds: 45  # ✅ Increased delay
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:  # ✅ Updated readiness probe
            httpGet:
              path: /health  # `/` se better hai agar app ke pass hai
              port: 3000
            initialDelaySeconds: 45  # ✅ Increased delay
            periodSeconds: 10
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: webapps
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
